language: python
env:
    PYTHONPATH: .
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
  - pip install .
script:
  - coverage run --source=django_presskit runtests.py
after_success:
  - coveralls
