language: python
env:
    PYTHONPATH: .
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run runtests.py --source=django_presskit
after_success:
  - coveralls
