language: python
env:
  PYTHONPATH: .
  matrix:
    - DJANGO='>=3.1,<3.2'
    - DJANGO='>=3.0,<3.1'
    - DJANGO='>=2.2,<3.0'
python:
  - 3.8
  - 3.7
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
  - pip install --pre django$DJANGO
  - pip install .
script:
  - coverage run --source=django_presskit runtests.py
after_success:
  - coveralls
