# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('based_in', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('analytics', models.CharField(max_length=200)),
                ('promoter_id', models.CharField(max_length=20)),
                ('founding_date', models.CharField(max_length=200)),
                ('press_contact', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('additional_links', models.ManyToManyField(to='django_presskit.AdditionalLink')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=300)),
                ('website', models.URLField()),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MonetizationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('press_can_request_copy', models.BooleanField()),
                ('promoter_id', models.CharField(max_length=20)),
                ('additional_links', models.ManyToManyField(to='django_presskit.AdditionalLink')),
                ('credits', models.ManyToManyField(to='django_presskit.Credit')),
                ('distribute_keyfile', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_distribute_keyfile', to='filer.File')),
                ('header_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_header_image', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Attachment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLogoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Attachment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=400)),
                ('website', models.URLField()),
                ('publication_name', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('embed_url', models.URLField()),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_video', to='filer.File')),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trailer',
            name='video_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.VideoType'),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='project_images', through='django_presskit.ProjectImageAttachment', to='django_presskit.Attachment'),
        ),
        migrations.AddField(
            model_name='project',
            name='logos',
            field=models.ManyToManyField(related_name='project_logos', through='django_presskit.ProjectLogoAttachment', to='django_presskit.Attachment'),
        ),
        migrations.AddField(
            model_name='project',
            name='monetization_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.MonetizationPermission'),
        ),
        migrations.AddField(
            model_name='price',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Project'),
        ),
        migrations.AddField(
            model_name='platform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Project'),
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Project'),
        ),
    ]
