# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0001_squashed_0006_company_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Attachment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='logos',
            field=models.ManyToManyField(related_name='company_logos', through='django_presskit.CompanyLogoAttachment', to='django_presskit.Attachment'),
        ),
    ]
