# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0001_squashed_0006_company_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='awards',
            field=models.ManyToManyField(blank=True, to='django_presskit.Award'),
        ),
    ]
