# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='additionallink',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionallink',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='award',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monetizationpermission',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monetizationpermission',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='price',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectimageattachment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimageattachment',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectlogoattachment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectlogoattachment',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='social',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videotype',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotype',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
