# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0002_auto_20180625_0005'),
        ('django_presskit', '0002_project_awards'),
    ]

    operations = [
    ]
