# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0003_merge_20180907_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvideo',
            name='video_type',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='video_type',
        ),
        migrations.AddField(
            model_name='trailer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='django_presskit.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyvideo',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VideoType',
        ),
    ]
