# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0004_auto_20180311_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_presskit.Company'),
            preserve_default=False,
        ),
    ]
