# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_presskit', '0005_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='promoter_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
